### ISSUE TITLE
Consider a JSON-LD style "language map" for the `title*` shape

### ISSUE THREAD

**Issue by BigBlueHat** [dret/I-D#104]
Originally proposed as part of https://github.com/dret/I-D/issues/89#issuecomment-415048808

The `title*` property might benefit from using a structure similar to [JSON-LD's language map](https://w3c.github.io/json-ld-syntax/#h-note-14) approach:
```json
{
  "title": "unknown language",
  "title*": {
    "en": "the english language value",
    "jp": "...if I knew Japanese...this would be in kanji..."  
   }
}
```

Checkout [ActivityStreams](http://activitystrea.ms/) JSON format (based on JSON-LD and in use in Mastodon and friends) for a similar approach: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-name

Advantages include;
 - not having to loop through the whole collection to find the title in the language you want
    - instead it becomes simply `link['title*'].jp` and detection becomes `if ('jp' in link['title*'])`
 - no "magic" array shapes
    - otherwise one has to know that `title*` contains a unique array in a very specific shape/order

**Comment by dret** [comment]
we have a new serialization now.
