### ISSUE TITLE
Add a note about line folding in linkset in headers

### ISSUE THREAD

**Issue by ibnesayeed** [dret/I-D#108]
When `linkset` is communicated using the `Link` header, one might fold (soft-wrap) each entry in a separate line with a white-space prefix for readability as linksets might be large. This is how it is illustrated in Figure 4 of the current draft. However, [RFC7230 section 3.2.4](https://tools.ietf.org/html/rfc7230#section-3.2.4) explicitly prohibits line-folding in HTTP headers (except in the `message/http` media type). This was also highlighted by @mnot in one of [his blog posts](https://www.mnot.net/blog/2014/06/07/rfc2616_is_dead).

While I am not suggesting that Figure 2, 4, and 6 be changed, I think a brief note somewhere with reference to RFC7230 section 3.2.4 will be helpful. Although, the responsibility of proper formatting of HTTP headers is out side of the scope of this (and every other HTTP-related RFC), repeating certain recommendations where a documented example has the potential to mislead the reader might be a good idea.

/cc @phonedude @hvdsomp

**Comment by dret** [comment]
On 2018-11-16 17:15, Sawood Alam wrote:
> While I am not suggesting that Figure 2, 4, and 6 be changed, I think a 
> brief note somewhere with reference to RFC7230 section 3.2.4 will be 
> helpful. Although, the responsibility of proper formatting of HTTP 
> headers is out side of the scope of this (and every other HTTP-related 
> RFC), repeating certain recommendations where a documented example has 
> the potential to mislead the reader might be a good idea.

agreed that a note here might be useful. thanks for pointing it out.

**Comment by dret** [comment]
done.
