### ISSUE TITLE
HTTP Problem namespace URI

### ISSUE THREAD

**Issue by dret** [dret/I-D#11]
the current draft uses a URN to identify the XML vocabulary (by namespace URI). there was some pushback against that, and the suggestion to use a HTTP URI instead. https://github.com/mnot/I-D/issues/147 talks about how that URN could be replaced by DOI URI (according to the new RFC 7669 spec), but that one of course also would not be a HTTP URI.

**Comment by asbjornu** [comment]
It would be very helpful if the URI was a resolvable HTTP URL.

**Comment by dschulten** [comment]
+1, especially since the XXX shows that the identifying string is yet to be defined. 
If the namespace URL ends with #, a full URL can easily identify a term in the vocab file (lesson learned from the discussion around IANA rel URLs).

**Comment by dschulten** [comment]
w3id.org might be an option,  and redirect to github pages?

**Comment by asbjornu** [comment]
@dschulten mnot/I-D#147 was closed with the following comment:

> *sigh* If this had come up a few months ago, sure, but there's already WG consensus and it's going to the IESG. You can bring this up in IETF Last Call, but I'd argue that the slight benefits of a HTTP URL are easily outweighed by breaking the people already using it.

So I guess we can try to raise this during IETF Last Call (I'm not quite sure how that process works, though), but it's highly unlikely that the URI is going to change.

**Comment by dret** [comment]
On 2015-11-04 09:53, Asbjørn Ulsberg wrote:
> @dschulten <https://github.com/dschulten> mnot/I-D#147
> <https://github.com/mnot/I-D/issues/147> was closed with the following
> comment:
>
>     /sigh/ If this had come up a few months ago, sure, but there's
>     already WG consensus and it's going to the IESG. You can bring this
>     up in IETF Last Call, but I'd argue that the slight benefits of a
>     HTTP URL are easily outweighed by breaking the people already using it.
>
> So I guess we can try to raise this during IETF Last Call (I'm not quite
> sure how that process works, though), but it's highly unlikely that the
> URI is going to change.

please keep in mind that this is about *the XML namespace URI*. since 
XML namespace URIs are identifiers only, there really shouldn't be such 
an issue with it being a non-HTTP URI.

**Comment by asbjornu** [comment]
@dret True, but don't you agree that it would be unfortunate and impractical to have different namespace identifiers for the XML representation and JSON(-LD) representation of the same resource?

**Comment by dret** [comment]
On 2015-11-04 13:00, Asbjørn Ulsberg wrote:
> @dret <https://github.com/dret> True, but don't you agree that it would
> be unfortunate and impractical to have different namespace identifiers
> for the XML representation and JSON(-LD) representation of the same
> resource?

i don't think so. XML is very specific to make a namespace URI an 
identifier only. it seems that JSON-LD is very keen on making it a 
resolvable reference (even though what's referenced would be an integral 
part of the spec and hopefully never ever change, so i am still not 
quite why it matters this much, other than for purity, but that's a 
different debate).

maybe it would look less ideal than reusing the same URI, but i 
certainly don't think that it would be "impractical". to be honest, i 
cannot think of one practical consequence. what do you think would 
happen if there were different URIs?

**Comment by asbjornu** [comment]
@dret I think having separate namespace URIs incurs more cognitive load. It makes it harder to identify that two different serializations of the same thing actually represents the same thing.

It will also lead to more errors. Having two namespace URIs will make (mis-) using them in the wrong serialization a mistake that is really easy to commit and something that is guaranteed to happen. We're going to see the XML URI used in JSON and vice versa. Consumers of the formats will have to build in support for these errors, which makes implementing HTTP Problem processors more complicated.

I also think it's wrong to look at a namespace URI as nothing more than an identifier, regardless of what [xmlns](http://www.w3.org/TR/REC-xml-names/) has specified. As soon as the URI is "out there", it's a huge missed opportunity to not make it dereferencable and ensure that what's hosted on that URI is a meaningful entrypoint into the format or protocol using the URI as its namespace.

And as soon as a URI looks familiar, people are going to try to dereference it. They don't care what the XMLNS specification say. If it looks like a URL, it should act like a URL and dereference to something describing what it is and point to specifications, documentation and such so people can discover everything there is to know about this from a normative and official place and not through a volatile Google search.

Once you have a dereferencable URI, you have an extension point that can ensure forward compatibility with things such as RDF. Without it, you don't, and people interested in having that sort of integration need to go through the relatively complicated and costly process of defining a mapping between the original format and URI to an RDF-compatible one.
