### ISSUE TITLE
rewrite link relation descriptions

### ISSUE THREAD

**Issue by dret** [dret/I-D#113]
note by @mnot (thanks!):

Just my personal .02 - 

It would be great if the link relations (both in this document and the other one) were written in terms of RFC8288.

E.g. instead of:
  Linking to a resource providing information about a resource's or service's retirement policy and/or information.
Something like:
  Identifies a resource that provides information about the context's retirement policy.

(We've been trying to make the use of terminology in the registry more consistent)

**Comment by mnot** [comment]
The important part was using terms like "context" to describe what the context of the link relation is.

**Comment by dret** [comment]
On 2018-11-26 22:31, Mark Nottingham wrote:
> The important part was using terms like "context" to describe what the 
> context of the link relation is.

ok, i have now mentioned the context everywhere. i hope this is more 
along the lines of what you were expecting.

**Comment by mnot** [comment]
That's better, thanks.

**Comment by mnot** [comment]
Are you going to resubmit?

**Comment by dret** [comment]
On 2018-11-27 23:51, Mark Nottingham wrote:
> Are you going to resubmit?

yes, but i have two more reviews i want to go through and edit the 
drafts before i resubmit. should be done sometime this week.

**Comment by dret** [comment]
assuming the second try was good enough and closing this issue.
