### ISSUE TITLE
Use example including 'anchor' with a fragment

### ISSUE THREAD

**Issue by csarven** [dret/I-D#116]
I think using one of the examples with an `anchor` including a fragment can diversify (at least visibly) what's possible - this is of course beside the definition of stating (or referring to RFC 8288) as to what an `anchor` value may be. So like the copyright example in https://tools.ietf.org/html/rfc8288#section-3.5 which refers to a particular part of the document, the following example is about the correction section in the document made by an author:

```json
{"href":"http://authors.example.net/johndoe",
  "anchor":"http://example.org/article?id=10.1371/journal.pone.0167475#amendment-0",
  "rel":["author"],"type":"application/rdf+xml"}
```

(or whatever example is more clear using `#`)

**Comment by dret** [comment]
sorry for leaving this open for so long. if you think this is somehow is essential, could you maybe explain why? otherwise we think that of course this can be done, but we're not quite sure why would have to point it out specifically.

**Comment by csarven** [comment]
As said, using diverse examples can (indirectly) help the reader. It is an editorial call.

**Comment by dret** [comment]
i'll leave it up to @hvdsomp to add examples if he feels the need. if not, let's close this one. it is the last open issue! yay!

**Comment by richsalz** [comment]
Please use https://github.com/ietf-wg-httpapi/linkset/issues/4
