### ISSUE TITLE
Use case - POSTing problem detail to 'issues' URL

### ISSUE THREAD

**Issue by leonardr** [dret/I-D#12]
I'm designing a system where a client reports errors by POSTing a problem detail (http://tools.ietf.org/html/draft-ietf-appsawg-http-problem-01) to an appropriate URL. There are a wide variety of domain-specific problems, each of which is assigned a URI that goes into the 'type' field of the problem detail. This lets me serve a single 'issues' link that can accept all kinds of problem reports.

IMO it might make sense to define separate 'abuse' and 'issues' link relations (similar to how email servers traditionally define 'abuse@' and 'postmaster@'), but beyond that point I think a detailed description of what exactly the problem is should go into the request entity-body.

I welcome any feedback on this design and hope this helps with the I-D.

**Comment by dret** [comment]
closing because the draft got dropped a long time ago.
