### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by reschke** [dret/I-D#124]
>    This draft should be discussed on the rfc-interest mailing list
>    (<https://www.rfc-editor.org/mailman/listinfo/rfc-interest>).

Nope. That's a mailing list about RFCs in general, not about particular technical proposals.

**Comment by dret** [comment]
thanks for the feedback. which one would you recommend?

**Comment by reschke** [comment]
http-wg...

**Comment by dret** [comment]
On 2019-11-05 07:19, Julian Reschke wrote:
> http-wg...

doesn't exist at the usual IETF places, could you point to it? thanks.

**Comment by reschke** [comment]
https://lists.w3.org/Archives/Public/ietf-http-wg/

**Comment by dret** [comment]
On 2019-11-05 07:51, Julian Reschke wrote:
> https://lists.w3.org/Archives/Public/ietf-http-wg/

thanks!
