### ISSUE TITLE
Register Profile URI for RDF HTTP Problem Reports?

### ISSUE THREAD

**Issue by dret** [dret/I-D#13]
http://www.iana.org/assignments/profile-uris/profile-uris.xhtml is a registry for profile URIs, created by @lanthaler via https://tools.ietf.org/html/rfc7284. maybe it might be appropriate to register a profile URI for the "RDF HTTP Problem Report vocabulary", and encourage its use?

**Comment by asbjornu** [comment]
@dret Sounds like a good plan!
