### ISSUE TITLE
content-warning: header or field

### ISSUE THREAD

**Issue by ioggstream** [dret/I-D#133]
## Note

Consider the following discussion about headers and fields https://lists.w3.org/Archives/Public/ietf-http-wg/2020JanMar/0216.html 

we can consider using `content-warning` to be a `field` and thus applicable both in `header` and `trailer` section. This is esp. true when the server knows about the presence of warnings *after* the creation of the response.

**Comment by andrecedik** [comment]
Very interesting consideration. Making warnings possible in a (chunked) trailer section seems like it should be possible, since warnings probably can also occur while post processing or doing an integrity check.
