### ISSUE TITLE
Add GS1 to the implementation status section

### ISSUE THREAD

**Issue by dret** [dret/I-D#139]

**Comment by dret** [comment]
probably addressed by https://github.com/dret/I-D/commit/a60b02b8a6a1a895d2cf90cab8f4c0861b110b23

**Comment by philarcher** [comment]
I'm happy to confirm that GS1 is happy with that text, thank you.

**Comment by hvdsomp** [comment]
added to the I-D

**Comment by philarcher** [comment]
We're making progress with our implementation. By the end of this month expect to see:
* The next iteration of the GS1 Digital Link standard in public review. It will say that its inclusion of Linkset is informative but only until such time as Linkset becomes an RFC when the citation will be normative. The text of the GS1 standard itself shouldn't need to change.
* We're already making progress with actual implementation and addition of our use of Linkset included in our resolver test suite.

More soon...
