### ISSUE TITLE
More repositories, please

### ISSUE THREAD

**Issue by asbjornu** [dret/I-D#14]
As I wrote in mnot/I-D#150, it will make it easier to collaborate on the RFC's you've contributed to if you separate each RFC/I-D into its own repository. Since there are a lot of RFC's and increasing interest in them, there's now quite a bit of activity in issues, discussions and pull requests that are mostly completely unrelated.

Even though it involves a bit of work, I think it would be wise to separate each RFC into its own repository, so they get their own revision history, their own related issues, pull requests, etc. Although that means each repository becomes very small, it will make everything a bit more organized and easier to follow. Perhaps not so much for you, but at least for everyone else who might not be interested in all of the ongoing I-D work, but just in that of a few specific RFC's.

In order to separate the repositories, you can quite easily [move a subdirectory of your current repository into a new repository](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/) and then [move all related issues to the new repository](https://github.com/google/github-issue-mover). I'd love to help you out, so please let me know if you think this is a good idea or not and whether you'd like help doing it.

**Comment by dret** [comment]
let me think about this a little bit. practically speaking, i don't like that this ends up creating a huge "flat space" of many repositories. i do like to have some hierarchy in that structure. but i do see your point that because of github's features and workflows, it makes sense to separate things into individual repositories.

**Comment by asbjornu** [comment]
Thanks. I don't want to burden you with a lot of overhead, but having a repository focus on "one thing" is kind of how GitHub works, so following that makes life a bit easier for collaborators like me, at least. :)

**Comment by dret** [comment]
i'll promise to try to label things diligently, but other than that i am going to pull an @mnot on this.
