### ISSUE TITLE
Support Link Hints?

### ISSUE THREAD

**Issue by dret** [dret/I-D#141]
the question is whether we should explicitly support "link hints". @hvdsomp added support for https://tools.ietf.org/html/draft-nottingham-link-hint in https://tools.ietf.org/html/draft-wilde-linkset-06, but we're concerned that we will have a dependency on a draft with a unclear timeline. @mnot, could you weigh in on that? thanks! (cc @RubenVerborgh)

**Comment by hvdsomp** [comment]
The profile negotiation effort (see [https://profilenegotiation.github.io/I-D-Profile-Negotiation/I-D-Profile-Negotiation.html](https://profilenegotiation.github.io/I-D-Profile-Negotiation/I-D-Profile-Negotiation.html)) builds heavily on Link Hints and, as such, an indication regarding its future would be very helpful in that context too. The profile negotiation work resorts under activities of the W3C Data Exchange Working Group, see [https://www.w3.org/2017/dxwg/wiki/Main_Page](https://www.w3.org/2017/dxwg/wiki/Main_Page). See also comments regarding Link Hints by @RubenVerborgh at [https://github.com/mnot/I-D/issues](https://github.com/mnot/I-D/issues).

**Comment by mnot** [comment]
Should know about the WG in the next ~few weeks; once it's established, it can talk about what documents to adopt.

**Comment by dret** [comment]
On 2020-07-29 10:03, Mark Nottingham wrote:
> Should know about the WG in the next ~few weeks; once it's established, 
> it can talk about what documents to adopt.

sounds good, thanks for the info.

**Comment by larsgsvensson** [comment]
@mnot wrote:
> Should know about the WG in the next ~few weeks; once it's established, it can talk about what documents to adopt.

Has there been a decision on the WG? We're looking at finalising the profile negotiation work in the W3C DXWG so we're eager to know if we'll be able to depend on link hints or not. Thanks for any hints!

**Comment by dret** [comment]
On 2020-09-25 17:12, Lars G. Svensson wrote:
> @mnot <https://github.com/mnot> wrote:
> 
>     Should know about the WG in the next ~few weeks; once it's
>     established, it can talk about what documents to adopt.
> 
> Has there been a decision on the WG? We're looking at finalising the 
> profile negotiation work in the W3C DXWG so we're eager to know if we'll 
> be able to depend on link hints or not. Thanks for any hints!

i think there hasn't been a formal decision so far, but i am still 
hopeful that the group will be established eventually. maybe @mnot can 
comment on the likelihood and the timing.

**Comment by mnot** [comment]
The WG charter is out for review, scheduled to end 10-10. If that goes smoothly it should be real shortly afterwards.

**Comment by dret** [comment]
hello @mnot.

On 2020-10-02 06:46, Mark Nottingham wrote:
> The WG charter is out for review, scheduled to end 10-10. If that goes 
> smoothly it should be real shortly afterwards.

great news, thanks! hoping for the best, that's only a week from now!

**Comment by larsgsvensson** [comment]
> great news, thanks! hoping for the best, that's only a week from now!
+1 to that!

**Comment by dret** [comment]
we decided to remove the dependencies on link hints in today's call with @hvdsomp. this way we can move forward without that dependency, and when/if link hints become finalized, we can update the linkset spec to also support link hints.
