### ISSUE TITLE
http-problem-rdf custom properties

### ISSUE THREAD

**Issue by dschulten** [dret/I-D#15]
Proposed I-D section about custom attributes, here is the json-ld playground with the example below: http://json-ld.org/playground/#/gist/0b07d129703003c46a35
For cloning:
https://gist.github.com/anonymous/0b07d129703003c46a35#file-markup-jsonld
# Custom attributes

JSON attributes without a linked data name are ignored in JSON-LD. Therefore, custom attributes like those mentioned by the http-problem I-D need to be mapped in the JSON-LD context to make them visible in the RDF model. The example below shows two custom attributes, balance and accounts.

```
{
  "@context": [
    "https://raw.githubusercontent.com/dret/I-D/master/http-problem-rdf/http-problem-context.jsonld",
    {
      "balance":"https://example.com/probs#balance",
      "accounts":{
        "@id":"https://example.com/probs#accounts",
        "@type":"@id"
      }
    }
  ],
  "type": "https://example.com/probs/out-of-credit",
  "title": "You do not have enough credit.",
  "detail": "Your current balance is 30, but that costs 50.",
  "instance": "/account/12345/msgs/abc",
  "balance": 30,
  "accounts": ["/account/12345",
                 "/account/67890"]
}
```

Conversion from JSON-LD to the canonical JSON model of application/problem+json happens by removing the JSON-LD context (the `@context` or the JSON-LD Link header) and by reading the resulting response as content type application/json.

To allow this conversion, a custom attribute name in JSON-LD is always the same as in the canonical problem+json representation. Also, applications SHOULD NOT introduce alias attribute names for type, title, detail and instance in JSON-LD representations.

JSON-LD does not map a JSON list of lists to RDF. Hence, a JSON-LD representation of an http-problem response does not map list of list attributes in the JSON-LD context either, with the effect that such custom attributes are not visible in the RDF model.

**Comment by asbjornu** [comment]
@dschulten Is this proposed specification text or a draft of ideas open for discussion? If the latter, I agree with everything stated. But considered as the former, I think the text needs to be formalized with [RFC 2119 wording](https://www.ietf.org/rfc/rfc2119.txt), among other things.

**Comment by dschulten** [comment]
It is meant as text which could end up in the I-D after thorough discussion how prescriptive the statements should be and if everything is correct. I used SHOULD NOT in one place where I thought it would be appropriate, but I have never authored a text conforming to RFC 2919. The 'must'  in the first paragraph slipped through ;-) 

How should we proceed, is it OK if I write a pull request for the draft with a rough outline where Custom Attributes could be one section? That would allow us to edit a common text base.

**Comment by asbjornu** [comment]
Yes, I think that's a good first step that gives us something concrete to discuss going forward. I'm just thinking; should the section be named **Custom Properties** or is the term *attributes* established in the RDF community? If so, which standard should we align our language with; JSON or RDF?

**Comment by dschulten** [comment]
In JSON-LD the JSON attributes are interpreted as RDF predicates or properties. Maybe it would be good to have a terms section which says that by attributes we mean JSON and by properties we mean RDF, and similar for JSON object vs. RDF individual etc.

**Comment by asbjornu** [comment]
Yes, that sounds like a good idea.
