### ISSUE TITLE
http-problem-rdf type attribute considerations

### ISSUE THREAD

**Issue by dschulten** [dret/I-D#16]
I see two issues with 'type':
- problem+json defines about:blank as default value of type. Using rdfs:type for 'type' would entail that about:blank is an rdf:Class and that the problem instance is an instance of about:blank. We can't really mean that
- RDF schema has no concept of default values, we would need an auxiliary vocab to specify a default value. It might make sense to say in the spec that applications MUST NOT omit the type attribute in RDF serializations and that its value MUST be about:blank if the application does not choose a different URI for type.

**Comment by asbjornu** [comment]
> problem+json defines about:blank as default value of type.

Yes, this is problematic.

> Using rdfs:type for 'type' would entail that about:blank is an rdf:Class and that the problem instance is an instance of about:blank. We can't really mean that

Can't we establish "about" as a vocabulary and "blank" as a void type of some sort?

> applications MUST NOT omit the type attribute in RDF serializations

I think this is a good compromise.

>  its value MUST be about:blank if the application does not choose a different URI for type

I'm not sure I understand what you mean with this. Would you care to provide some examples?

**Comment by dschulten** [comment]
We have two possibilities to use the type attribute. 

1. It could be a URI string as currently proposed. In that case about:blank is a possible value, because it is a URI and hopefully nothing too weird would be inferred from that by a reasoner, other than that the value of 'type' is a resource that dereferences to a blank page. The remaining issue is the default value. Since rdfs cannot express that, we could make it a requirement that applications which choose not to define a type URI must do so by setting type to about:blank. 

2. It could be transformed to an @type attribute, i.e. it would be rdfs:type. Tempting, because then one could have subtypes of HttpProblem and vocabularies for them. But my current feeling is, since the original type is really just an identifier string it would be difficult to map existing type URIs and whatever they dereference to into something meaningful in RDF.

**Comment by asbjornu** [comment]
I think I understand better now, but could you please provide an example of alternative 2 as well?

**Comment by dschulten** [comment]
Sure, http://tinyurl.com/qfbveyn. I was a bit lazy and used the "last context wins" rule to override the type definition from the context.jsonld. If we were to make the type attribute an rdfs:type, that statement would go into the published context file. 

Thinking about the requirement to assign about:blank to the type attribute - maybe that is not such a good idea because it makes it impossible to map a problem+json without type attribute to a json-ld, simply by applying a context. The conversion would have to materialize the about:blank. Would it be an option to state that applications which expect a type URI MAY use about:blank if no type is defined in the response?

**Comment by asbjornu** [comment]
Thanks. How would the latter example look like if it had `"type" : "about:blank"`?

**Comment by dschulten** [comment]
Rfc6694 establishes 'about' as well-known URI scheme, so it might be valid to treat about:blank as URI which identifies a resource that describes a problem type, within the logic of option 1 - -  only, the description is blank. 

Concerning option 2, since the RDF 1.1 recommendation says that
> A triple of the form:
>
>R rdf:type C
>
>states that C is an instance of rdfs:Class and R is an instance of C.
> The rdfs:range of rdf:type is rdfs:Class.

a triple like

`<http://example.com/probs/123245> <rdf:type> <about:blank>. `

seems slightly unorthodox O:-)  because neither do we want to say that the problem no.  123245 is an instance of the class of blank browser pages, nor am I sure if it were correct to infer that the thing identified by about:blank qualifies as an rdfs:Class which encompasses individuals that belong to it. Ok, the latter might pass as merely unorthodox, but the former is outright hilarious ;-)

**Comment by dschulten** [comment]
Option 2 with `"@type":"about:blank"` statement that shows the nonsense that comes out of option 2: http://tinyurl.com/nnf4det

**Comment by dschulten** [comment]
The choice to let type be an identifier for a certain kind of problems and allowing about:blank to be one of them is the root of this confusion. Too bad that it seems to be too late for this kind of feedback now, being after last call and all.

**Comment by asbjornu** [comment]
> because neither do we want to say that the problem no. 123245 is an instance of the class of blank browser pages

Haha, no.

> nor am I sure if it were correct to infer that the thing identified by about:blank qualifies as an rdfs:Class which encompasses individuals that belong to it

Hm. Why not? Can't we define that semantic in the specification of http-problem-rdf?

> Ok, the latter might pass as merely unorthodox, but the former is outright hilarious ;-)

Indeed! :smile:

> The choice to let type be an identifier for a certain kind of problems and allowing about:blank to be one of them is the root of this confusion. Too bad that it seems to be too late for this kind of feedback now, being after last call and all.

I know. I wish I heard about both HTTP Problem and Hydra a year ago or more.
