### ISSUE TITLE
No profile parameter allowed for application/problem+json? 

### ISSUE THREAD

**Issue by dschulten** [dret/I-D#17]
Custom http-problem attributes could be publicly specified by a profile, either as rel of a Link header or as media-type parameter. I am not sure if the http-problem draft wants to avoid that or discourage it in its IANA considerations where it seems to rule out a profile parameter for problem+json.

If not, such a profile link could converge nicely with an URL prefix for custom problem properties in RDF.

**Comment by dret** [comment]
On 2015-11-04 20:13, Dietrich Schulten wrote:
> Custom http-problem attributes could be publicly specified by a profile,
> either as rel of a Link header or as media-type parameter. I am not sure
> if the http-problem draft wants to avoid that or discourage it in its
> IANA considerations where it seems to rule out a profile parameter for
> problem+json.

that's an interesting point. i cannot recall that we ever discussed to 
have a profile parameter for the media type. a quick search in @mnot's 
repo did not yield any results. such a change very likely would be a bit 
late given the current status, but it does sound like an interesting idea.

> If not, such a profile link could converge nicely with an URL prefix for
> custom problem properties in RDF.

a profile URI specifically is just an identifier (like an XML namespace 
URI) and thus shouldn't be used as a prefix. but it could be a nice way 
to identify specific ways in which extensions are being used.

**Comment by dschulten** [comment]
How do you read this:
> This specification defines two new Internet media types [RFC6838
      Type name: application
      Subtype name: problem+json
      Required parameters: None
      Optional parameters: None; unrecognised parameters
                           should be ignored

Does it mean that parameters are not allowed and that clients should ignore them? I think that would not be a problem if clients can still look for public error type profiles in the Link headers. The profile registry could be a place to register such types. 

The http-problem suggests to use an existing error type, if possible. No registry for error types is established by http-problem. Has it been discussed how people would find existing error types? 

I understand that the profile URI is an identifier and its presence tells the client that it can expect special semantics in the representation, without following that URL. But why should it not be used as a linked data URL prefix, so as to derive more sub-identifiers from a base identifier? Technically no need to dereference here, either.

**Comment by asbjornu** [comment]
> But why should it not be used as a linked data URL prefix, so as to derive more sub-identifiers from a base identifier? Technically no need to dereference here, either.

I also wonder about this and wrote quite a bit about it in #11. The fact that an URI only "needs" to be an identifier should not exclude its potential usage for other things.

When making the URI a dereferenceable HTTP URL incurs little cost on the original creation of it, while it incurs a huge cost on those who want to integrate it in environments where a dereferenceable HTTP URL is required (or at least extremely beneficial) if it is not dereferenceable, I find the continued insistence on creating undereferenceable URIs strange.

**Comment by dret** [comment]
On 2015-11-05 13:51, Dietrich Schulten wrote:
> Does it mean that parameters are not allowed and that clients should
> ignore them? I think that would not be a problem if clients can still
> look for public error type profiles in the Link headers. The profile
> registry could be a place to register such types.

afaict, if a media type does not define a parameter, then it is not ok 
to use one (i.e., make one up). that's my reading of how this works.

> The http-problem suggests to use an existing error type, if possible. No
> registry for error types is established by http-problem. Has it been
> discussed how people would find existing error types?

yes. the conclusion was to not try to have decentralized global 
extensibility, and instead rely on local names and, if anything ever did 
become a new standard, a new media type.

> I understand that the profile URI is an identifier and its presence
> tells the client that it can expect special semantics in the
> representation, without following that URL. But why should it not be
> used as a linked data URL prefix, so as to derive more sub-identifiers
> from a base identifier? Technically no need to dereference here, either.

nobody can keep you from doing this, of course, but profile URIs are 
defined to be identifiers and only identifiers. keep in mind that if a 
profile URI identified an extension, then that's all that's needed for 
the JSON and XML representations. and people defining extensions might 
not have the RDF representation in mind at all. so depending on this 
concatenation to work and yield meaningful URIs would be a risky bet.

**Comment by dret** [comment]
On 2015-11-05 16:26, Asbjørn Ulsberg wrote:
>     But why should it not be used as a linked data URL prefix, so as to
>     derive more sub-identifiers from a base identifier? Technically no
>     need to dereference here, either.
> I also wonder about this and wrote quite a bit about it in #11
> <https://github.com/dret/I-D/issues/11>. The fact that an URI only
> "needs" to be an identifier should not exclude its potential usage for
> other things.

in theory, yes, in practice, the result is that implementation start to 
blindly assume that a URI they find in some place is more than just an 
identifier, and in some limited scenarios that might actually be true. 
but those implementations tend to fail when the URIs actually are 
nothing but identifiers.

> When making the URI a dereferenceable HTTP URL incurs little cost on the
> original creation of it, while it incurs a huge cost on those who want
> to integrate it in environments where a dereferenceable HTTP URL is
> required (or at least extremely beneficial) if it is not
> dereferenceable, I find the continued insistence on creating
> undereferenceable URIs strange.

yes, i can see that. nobody insists on that, though. all that happens is 
that by definition some URIs are just identifiers (and it's a good thing 
to make that explicit, because links and identifiers are two different 
things). when that happens, using a non-HTTP URI simply is fair game. 
anybody who has a problem with that should take a long and hard look at 
their stack.
