### ISSUE TITLE
add provisional/permanent pattern

### ISSUE THREAD

**Issue by dret** [dret/I-D#24]
comment via twitter by @gklyne:

"is it worth mentioning the provisional/permanent pattern used for uri schemes and msg headers? Where provisional is primarily for documentation per your list of reasons?"

**Comment by dret** [comment]
yes, i think this is a good idea. where would you add it? is that a good for the current why/when/how structure, or would it make sense to add a fourth section about design/management options?

**Comment by gklyne** [comment]
Good question.  Off-the-cuff, I think it's a bit of both (i.e. rationale and management).

----

The original intent of introducing the permanent/provisional pattern was to lower the bar for registration (of message headers), without making every registered value somehow into an "IETF standard".  In my view, feelings in the IETF then were more protective than they are now, and I perceive something of a shift towards more relaxed registration (which I support in broad terms, but think it needs to be considered on a case by case basis taking into account the considerations raised in the draft).

One thing we did learn along the way is that having separate registries for provisional and permanent registries was not such a good idea, as it caused fragmentation.  Hence URI schemes recently moved to having a status field which can be "provisional".

Something else here on the "provisional" vs "endorsed" axis - I've come across a couple of cases where permanent registration has been attempted via the route of an ISE RFC which avoids the need for any kind of formal IETF review.  (Back in the day, IIRC, independent RFC submissions were still last-called in the IETF.)  This means that the criteria "RFC publication", which has sometimes been used, cannot be treated as equivalent to, say, "IETF consensus".

----

Coming back to your question:  I think it might be a useful exercise to see if rationale can be separated from management options (possibly including discussion of a frequently suggested alternative, which is to maintain a publicly editable wiki as an alternative to an IANA registry).  I think it might even be possible to simplify the different rationales that might be invoked from the mechanisms that can be used to implement them.  On this basis, I can imagine that a provisional/permanent registry distinction becomes a management option (where the rationale is to be able to distinguish community approved/endorsed specifications from, say, private experiments, while also maintaining discoverable public documentation of values that may appear in the wild).

**Comment by gklyne** [comment]
BTW, flowing up on the ISE RFC concern, there's a comment of mine made in another context: https://mailarchive.ietf.org/arch/search/?q=draft-iab-rfc5741bis&gbt=1&f_list=ietf#

**Comment by dret** [comment]
> I think it might even be possible to simplify the different
> rationales that might be invoked from the mechanisms that can be used to
> implement them. On this basis, I can imagine that a
> provisional/permanent registry distinction becomes a management option
> (where the rationale is to be able to distinguish community
> approved/endorsed specifications from, say, private experiments, while
> also maintaining discoverable public documentation of values that may
> appear in the wild).

https://github.com/dret/I-D/commit/15029a17f72a926ce4fd26695abb7f3a4b205c81 
is the first attempt to get some content into the why/when/how sections. 
and maybe that structure isn't the best idea to begin with, but that was 
my first goal, to get first complete draft with those aspects.

the "how" part is tricky. there are parts about the management (the ones 
you're mentioning), and some about usage of registry contents. but these 
are not independent, right? anyway, thanks for the feedback and i hope 
this is going somewhere!

**Comment by dret** [comment]
picking one interesting tidbit here (more on the other parts later):

On 2016-02-03 1:55 , gklyne wrote:
> Coming back to your question: I think it might be a useful exercise to
> see if rationale can be separated from management options (possibly
> including discussion of a frequently suggested alternative, which is to
> maintain a publicly editable wiki as an alternative to an IANA
> registry).

that's exactly the main goal of this structured discussion in the draft, 
and that's the thing that's often not done well in the current debates. 
for example, for the RFC 5988 link relation type registry, the authors 
of HTML5 expressed frustration over how that registry was operated, and 
then quickly decided to establish their own registry in a wiki, 
effectively forking a previously unified registry.

the confusing part about this was that the solution (a wiki is good! we 
don't like the current requirement to send an email!) was put in front 
of looking at goals and solutions. ironically, in the end a wiki needs 
some "process" as well, only that now this is not really well-defined.

in this case, it seemed to me that the concerns of some user group with 
a specific implementation were not separated from the goals and maybe 
alternative ways of how to improve or change the implementation. in the 
long term, this probably hurts the community more than it helps, so 
having a more disciplined way of discussing design goals and options, 
and then on their implementation, might be helpful.

**Comment by gklyne** [comment]
I think that's a great goal, and there has been a small amount of behind-the-scenes discussion of this (though none recently that I know of).  Preparing an I-D seems to be the right way to progress this.  It wasn't obvious to me from my initial read through that this was your intent.

It did occur to me, scanning through the various reasons you list for defining a registry, that very few of them are actually technical requirements (https://tools.ietf.org/html/draft-wilde-registries-01 section 3.2 and maybe 3.7).  The rest are social, or management concerns.  Your comment about  "a wiki needs some process as well" resonated strongly with me, so +1 there.

Once you get into this territory, the established practices of an existing community do have some weight, IMO.  The IETF has a long history of doing things in email, and having an email address represents the (technical) low bar of entry to IETF participation. Further, I don't think there are any short-cuts to genuine consensus building (as opposed to creating technical solutions).  I guess the load imposed by registration mechanisms should align with the amount of consensus they are expected to reflect.

(But I suspect we're now drifting off-topic for this issue...?)

**Comment by dret** [comment]
https://github.com/dret/I-D/commit/7ef7df39b4ba9d5a18046f5330d0bbb2ea6c12ae starts a new section which also will discuss the issue raised here.

**Comment by dret** [comment]
@gklyne, i have added the examples and please reopen this issue (or open a new one) if you think the discussion needs to be improved. i am still working on the section with the examples, and will generate new TXT/HTML versions when i am done with this. thanks again for raising this issue, i think it's a very useful addition to the document.

**Comment by dret** [comment]
as promised, https://github.com/dret/I-D/commit/e350894d431cd1240460b1482cde320d88a27b69 is the final edit of the new section, https://github.com/dret/I-D/commit/d7ecbb8c7f9de8da939848b38d26a71f1f7ebf6f the updated TXT/HTML. feedback very welcome!

**Comment by dret** [comment]
On 2016-02-03 10:55, gklyne wrote:
> Coming back to your question: I think it might be a useful exercise to
> see if rationale can be separated from management options (possibly
> including discussion of a frequently suggested alternative, which is to
> maintain a publicly editable wiki as an alternative to an IANA
> registry). I think it might even be possible to simplify the different
> rationales that might be invoked from the mechanisms that can be used to
> implement them. On this basis, I can imagine that a
> provisional/permanent registry distinction becomes a management option
> (where the rationale is to be able to distinguish community
> approved/endorsed specifications from, say, private experiments, while
> also maintaining discoverable public documentation of values that may
> appear in the wild).

the latest update should address this a little. not sure it really is 
what you were looking for, though. but for RFC 5988, for example, i 
think it's neat that unregistered values, by virtue of being URIs, have 
the capability to document themselves. the down side here is that they 
can never become registered values, because they don't fit the syntax 
requirements for being a registered value (simple strings only).

**Comment by dret** [comment]
On 2016-02-08 11:58, gklyne wrote:
> I think that's a great goal, and there has been a small amount of
> behind-the-scenes discussion of this (though none recently that I know
> of). Preparing an I-D seems to be the right way to progress this. It
> wasn't obvious to me from my initial read through that this was your intent.

then this should be made clearer. i think there are many valuable 
lessons to be learned from experience and existing practice/problems; 
the main challenge may be to present that in a digestible way that spec 
authors would be willing to read and follow.

> It did occur to me, scanning through the various reasons you list for
> defining a registry, that very few of them are actually technical
> requirements (https://tools.ietf.org/html/draft-wilde-registries-01
> section 3.2 and maybe 3.7). The rest are social, or management concerns.
> Your comment about "a wiki needs some process as well" resonated
> strongly with me, so +1 there.

i completely agree that many/most are non-technical issues, and i'd 
think that a final version of this draft should make this very clear. it 
may take a better intro and a better separation of discussions to make 
this very clear to readers.

> Once you get into this territory, the established practices of an
> existing community do have some weight, IMO. The IETF has a long history
> of doing things in email, and having an email address represents the
> (technical) low bar of entry to IETF participation. Further, I don't
> think there are any short-cuts to genuine consensus building (as opposed
> to creating technical solutions). I guess the load imposed by
> registration mechanisms should align with the amount of consensus they
> are expected to reflect.

it's just that the load is perceived very individually. for some people, 
email is simple and robust. for others, it seems obscure with a need to 
subscribe to lists and locate list archives. so i think that you're 
right generally speaking, but a lot of individual perspective/preference 
plays into finding the balance that people perceive as appropriate.

> (But I suspect we're now drifting off-topic for this issue...?)

well, definitely a bit more meta. but very useful. thanks.
