### ISSUE TITLE
DNS as a "registry"

### ISSUE THREAD

**Issue by dret** [dret/I-D#29]
would it make sense to discuss DNS as a "registry", and how the different record types can be seen as a way how the DNS infrastructure supports a variety of registries?

**Comment by dret** [comment]
this could be added as just another example in the examples section, but currently it only contains IANA-based registries, so it would probably require a longer explanation of why DNS can be considered a registry as well, and which aspects of it are different from the more typical IANA examples.

**Comment by asbjornu** [comment]
I think this makes a lot of sense.

**Comment by dret** [comment]
ok, #30 is a new issue for adding a non-IANA registry example. any pointers to non-IANA/non-DNS registries in IETF specs are very welcome!
