### ISSUE TITLE
Use RDF 3688 URI?

### ISSUE THREAD

**Issue by dret** [dret/I-D#34]
RFC 3688 establishes a registry for a variety of "schemas" for IETF specs, including RDF vocabularies. It would be possible to use register the "HTTP Problem RDF Vocabulary" and thus make sure that it has a well-defined and stable identifier. The downside is that the identifiers are not dereferencable, but since the schema is part of the I-D/RFC, this is not a problem on the technical level.

**Comment by asbjornu** [comment]
I haven't heard of RFC 3688 before. What implications does this have? How would the technical implementation look like?

**Comment by dret** [comment]
On 2016-03-02 23:08 , Asbjørn Ulsberg wrote:
> I haven't heard of RFC 3688 before. What implications does this have?
> How would the technical implementation look like?

it simply means that the "namespace URI" (which for RDF actually is a 
URI prefix) would be a URN. the RFC defines a pattern for that, so it 
would look roughly like this: urn:ietf:params:rdf:ns:homedoc

(https://github.com/dret/I-D/commit/1f4796810ea92ead324f250f23230249b9f319e2 
has made this change for the XML namespace already.)

**Comment by asbjornu** [comment]
Ah. I'm not a fan, but you probably know that already. :wink:
