### ISSUE TITLE
Xref to GitHub versions needs fix in .txt version "draft-wilde-updating-rfcs-00"

### ISSUE THREAD

**Issue by robincover** [dret/I-D#37]
Text says: "Online access to all versions and files is available on github [2]."

Text at "[2]" seems to reference nothing on GitHub

{ Postel, J. and J. Reynolds, "Instructions to RFC Authors",
              RFC 2223, DOI 10.17487/RFC2223, October 1997,
              http://www.rfc-editor.org/info/rfc2223}

**Comment by dret** [comment]
that looks like a new bug in xml2rfc; thanks for noticing (and finding the github version even though it wasn't linked...).

**Comment by dret** [comment]
not sure https://github.com/reschke/xml2rfc/issues/12 was filed against the right version of xml2rfc, but we'll figure it out eventually. thanks for noticing and taking the time to let me know!

**Comment by reschke** [comment]
No, this isn't the code that breaks for you. You need to report the problem at https://trac.tools.ietf.org/tools/xml2rfc/trac/report

**Comment by dret** [comment]
ha! seems like i had reported that specific bug a while ago already, but nothing ever happened. https://trac.tools.ietf.org/tools/xml2rfc/trac/ticket/308
@levkowetz, are there any plans to fix it, or is there a workaround? thanks!

**Comment by dret** [comment]
On 2016-09-15 01:47, Julian Reschke wrote:
> No, this isn't the code that breaks for you. You need to report the
> problem at https://trac.tools.ietf.org/tools/xml2rfc/trac/report

i vaguely remember getting some feedback back then about this not 
getting fixed because something new/better/improved would come along 
very soon. anyway, seems like this has been reported for a while now, 
but i am not even sure whether somebody looks at these reports, let 
alone does something about them?

**Comment by dret** [comment]
in the light of xml2rfc having had this bug for a long time, the usual workaround seems to be to use symbolic references. that simply routes around the numbering bug. @levkovetz and @reschke, if there are any plans to fix the bug (or plans to not fix it), it would be great to get some feedback on the reported bug in the tracker.
