### ISSUE TITLE
Confused about difference between relation name and link relation type

### ISSUE THREAD

**Issue by darrelmiller** [dret/I-D#5]
In this document https://github.com/dret/I-D/blob/master/service-link-rel/draft-wilde-service-link-rel-00.txt#L243 a link relation type is registered as "link-doc".  However, the relation name is identified as "service-doc".

Why two different names?  Which one do I use in a rel value?

**Comment by dret** [comment]
that's an easy one: thanks for spotting the typos! fixed here: https://github.com/dret/I-D/commit/ffd5b90df4e8ca1abd9c0742af081b9d8b9da68a
