### ISSUE TITLE
fix request URI

### ISSUE THREAD

**Issue by dret** [dret/I-D#50]
`GET /links/http://example.org/resource1 HTTP/1.1` is used in one of the examples. i am not quite sure what it is supposed to look like, but this looks definitely wrong.

**Comment by hvdsomp** [comment]
On Jan 30, 2017, at 15:49, Erik Wilde <notifications@github.com> wrote:
> 
> GET /links/http://example.org/resource1 HTTP/1.1 is used in one of the examples. i am not quite sure what it is supposed to look like, but this looks definitely wrong.
> 
These kind of URIs are abundant in web archiving, see e.g. Internet Archive. We're requesting links pertaining to http://example.org/resource1.  Would you prefer a query notation i.e. 
> GET /links?URI=http://example.org/resource1
> 

Btw I saw your other mail re blog. I'm sick in bed so it may take a few days until I get to that. 

Cheers

Herbert

**Comment by dret** [comment]
take your time and get well! cheers, dret.

**Comment by dret** [comment]
it seems like -02 switched to URI query strings, which probably makes things a little easier to read. if that's true and the plan is to stick to this alternative syntax, we can close this issue.

**Comment by dret** [comment]
this was resolved quite a while ago. closing.
