### ISSUE TITLE
Add "Sunrise" option

### ISSUE THREAD

**Issue by dret** [dret/I-D#51]
it might be useful to have the option of also announcing when a resource is planning of becoming accessible again. This could be an optional field in the `Sunset` header, or it could be a separate `Sunrise` header. either way, this would make it possible for services to announce scheduled downtimes where both start and end of the downtime are known in advance.

**Comment by asbjornu** [comment]
Perhaps an expected status code should be possible to configure too, so I know how to identify that "yes, the resource is in fact gone". Something like `Sunset: <http date>; status=410`.

**Comment by dret** [comment]
On 2017-03-01 08:24, Asbjørn Ulsberg wrote:
> Perhaps an expected status code should be possible to configure too, so
> I know how to identify that "yes, the resource is in fact gone".
> Something like |Sunset: <http date>; status=410|.

interesting idea, but in which way would that be helpful? maybe the most 
likely candidates here would be 404 and 410, but i am wondering what a 
client would want to do with this information?

**Comment by asbjornu** [comment]
It would know that when the resource is sunset, but responds with a different status code (say `500`), it's an error. Why would you request a sunset resource you might ask? Without the `Sunrise` header, it's a necessity to figure out when it's accessible again.

But even with the `Sunrise` header, the RFC 822 date format only allows for second precision, and with time zone conversions, DST issues, etc., there's a few things related to timing that might be off. Being able to know by the resource's response whether it's now online again or not is a nice assurance.

**Comment by dret** [comment]
On 2017-03-02 11:00, Asbjørn Ulsberg wrote:
> It would know that when the resource is sunset, but responds with a
> different status code (say |500|), it's an error. Why would you request
> a sunset resource you might ask? Without the |Sunrise| header, it's a
> necessity to figure out when it's accessible again.

the original motivation were resources that simply disappear. these may 
be decommissioned APIs, or specific resources in workflows that have 
limited lifetimes by design, such as "you can finalize this pending 
order for one day but then it will be gone". for these cases there is no 
sunrise.

> But even with the |Sunrise| header, the RFC 822 date format only allows
> for second precision, and with time zone conversions, DST issues, etc.,
> there's a few things related to timing that might be off. Being able to
> know by the resource's response whether it's now online again or not is
> a nice assurance.

i'd say if the resource simply doesn't respond or responds with some 
5xx code, something is not normal.

i would expect both headers to act as hints for clients to implement 
smarter client behavior. but in the end, clients still have to figure 
out if they can interact with the resource as intended or not. both 
headers simply help to maybe raise alerts, and to maybe be smarter when 
it comes to retrying or aborting.

**Comment by dret** [comment]
this issue may overcomplicate things. probably closing this in a little while unless there is concrete interest in using this in implementations.

**Comment by dret** [comment]
another possibility would be to simply things and say that instead of introducing a `Sunrise` header, servers who want to advertise that a resource might become available again *after* the `Sunset` can also include a [`Retry-After`](http://webconcepts.info/concepts/http-header/Retry-After) header. that way, we don't have to introduce a new header field. this could just become a section in the draft that recommends this as a pattern if people are looking for guidance how to handle a case where resources become unavailable but might become available again.

**Comment by dret** [comment]
getting close to closing this in favor of getting the RFC published without additional complications. anybody objecting make concrete suggestions now, or forever stay silent!

**Comment by dret** [comment]
closing this as part of the final RFC push.
