### ISSUE TITLE
Add status code guidance?

### ISSUE THREAD

**Issue by dret** [dret/I-D#53]
Would it be helpful to add some guidance about which status codes to use specifically after a resource has be sunsetted? for example, if a service keeps track of these resources, it could use `410` to indicate that this resource previously existed. if a service does not keep track or does not want to reveal the fact that a resource previously existed, `404` might be a better choice.

**Comment by asbjornu** [comment]
I think this makes sense. 👍

**Comment by dret** [comment]
getting close to closing this in favor of getting the RFC published without additional complications. anybody objecting make concrete suggestions now, or forever stay silent!

**Comment by dret** [comment]
closing this as part of the final RFC push.
