### ISSUE TITLE
Transitive Linksets

### ISSUE THREAD

**Issue by dret** [dret/I-D#55]
the spec should be clear about linkset transitivity. i.e., if a linkset contains a linkset link, what does this mean? by definition, that second-order linkset would identify links pertaining to the *linkset resource* (i.e., not the origin resource). however, there's nothing keeping that second-order linkset from containing links in which the origin resource participates.
in the end, it will be up to implementations to decide what to do about transitivity. the spec simply should mention that this case exists, and what it means on the technical level (as outlined above).

**Comment by hvdsomp** [comment]
Interesting one. And it might be worth to mention this indeed.

Here's my take on it:
- a linkset link provided by a linkset resource points to links pertaining to the linkset resource, i.e. in this case the linkset resource is itself also an origin resource
- if the response from the linkset resource is so big as to require paging, there are other links that can be used for that purpose, e.g. next

**Comment by dret** [comment]
agreed on (1), and thinking that (2) is a different issue. i like the language we have in `-02`, let's see if we get any feedback or request for clarifications.

**Comment by dret** [comment]
unless there are any objections, i think the language we have now is good enough and we can close this issue. please feel free to do so if you agree, @hvdsomp.

**Comment by dret** [comment]
closing since this has been sitting idle for long enough.
