### ISSUE TITLE
"Link Set" versus "Linkset"

### ISSUE THREAD

**Issue by dret** [dret/I-D#58]
the issue is whether instead of using "link set" as the terminology, we shouldn't switch to "linkset". i like the idea because then it's more like a well-defined keyword that's easy to recognize, and not so much a regular use of language. for now, the draft uses "link set" as the term and `linkset` only in the places where machine-readable labels are used (link relation type and media types).

**Comment by dret** [comment]
it seems that @hvdsomp's preference is to keep "link set". if so, please confirm and close, i can definitely live with that option. thanks.

**Comment by hvdsomp** [comment]
Yes, I think "link set" does work, so let's stick to it.

**Comment by dret** [comment]
On 2017-08-03 01:49, Herbert Van de Sompel wrote:
> Yes, I think "link set" does work, so let's stick to it.

excellent, thanks!
