### ISSUE TITLE
Machine-readable explanation

### ISSUE THREAD

**Issue by dret** [dret/I-D#60]
It would be possible to include machine-readable information about the reason for the URI's disappearance. This could either be done inline (maybe name/value pairs), and/or by reference to a URI that will dereference to machine-readable information.  (there's an issue about human-readable explanations as well: #59)

**Comment by philsturgeon** [comment]
Part of me thinks that so long as good machine readable metadata can be provided, then human readable text will not be so useful. 

As you spotted in tweets, I've got `+Deprecated (date: bla, message: 'Endpoint /api/v2/companies has been deprecated, please use `/api/v3/companies`)`. My goal here is to pair client-side middleware to the call, to detect this header and panic in the console in dev/test/stag. 

I can generate those messages easily enough from the machine readable data, but ofc I might be missing other use cases. 

SerialSeb on HTTP APIs Slack was talking about utilizing `Link` for this, which could be a good way to pair things up.

```
Link: <http://acme.com/api/v3/companies>;rel=sunset
```

Is it a bit off to suggest "Sunset header MAY be paired with a Link and rel of "sunset" to help users find the content? 

I'd worry that if Location started popping up, some not-so-well clients might start following it, but Location may well be better. 

The other thing is: do we want a URL to send humans to to read more? This could be a link to the human documentation for the new endpoint, or a blog article explaining the changes, or a CHANGELOG, etc.

```
Link: <http://acme.com/api/v3/companies>;rel=sunset, <http://acme.com/api-docs/v3/companies.html>;rel=sunset-details
```

**Comment by dret** [comment]
On 2017-08-02 09:27, Phil Sturgeon wrote:
> Part of me thinks that so long as good machine readable metadata can be 
> provided, then human readable text will not be so useful.

probably true, i would mostly see sunset info as being handled by code 
that then makes some decisions about what to do, which might or might 
not include raising an alarm to humans.

> As you spotted in tweets, I've got |+Deprecated (date: bla, message: 
> 'Endpoint /api/v2/companies has been deprecated, please 
> use|/api/v3/companies|)|. My goal here is to pair client-side middleware 
> to the call, to detect this header and panic in the console in 
> dev/test/stag.

for console info, using generic text such as "Upcoming HTTP Sunset 
detected at http://example.org/: *date*" might be good enough.

> I can generate those messages easily enough from the machine readable 
> data, but ofc I might be missing other use cases.

exactly.

> SerialSeb on HTTP APIs Slack was talking about utilizing |Link| for 
> this, which could be a good way to pair things up.
> |Link: <http://acme.com/api/v3/companies>;rel=sunset |

to me, this is a reflection of the semwebby reflex to turn everything 
into triples and then by extension into links. to me, links should be 
reserved for proper (hypermedia) links, and therefore i prefer to 
represent other concepts in different ways. but that's definitely mostly 
a difference in style, and modeling preference.

> Is it a bit off to suggest "Sunset header MAY be paired with a Link and 
> rel of "sunset" to help users find the content?

that would be one way to go, in which case we could add a sunset link 
relation to the draft. i would probably still prefer for the timestamp 
(the operationally actionable info) to remain an HTTP header field, but 
the link relation could always be used to link to "sunset details" 
resources which then could use any media type (potentially a complete 
"deprecation/migration details" document that would explain how to 
handle the sunset and a possible migration to a new service).

> I'd worry that if Location started popping up, some not-so-well clients 
> might start following it, but Location may well be better.

i'd say if you simply migrate resource between URIs, then don't bother 
using sunset and simply use basic HTTP redirects. maybe that could be 
part of the spec as well: when *not* to use sunset and use simpler 
approaches instead.

> The other thing is: do we want a URL to send humans to to read more? 
> This could be a link to the human documentation for the new endpoint, or 
> a blog article explaining the changes, or a CHANGELOG, etc.

yes, this could be the case for a "sunset" link rel, which should be 
media type agnostic. if you think that's a good idea, please feel free 
to raise an issue. thanks!

**Comment by philsturgeon** [comment]
👍 🌮 #72

**Comment by dret** [comment]
getting close to closing this in favor of getting the RFC published without additional complications. anybody objecting make concrete suggestions now, or forever stay silent!

**Comment by dret** [comment]
closing this as part of the final RFC push.
