### ISSUE TITLE
New URI

### ISSUE THREAD

**Issue by dret** [dret/I-D#61]
If the resource's new URI is known (for example when a service is migrating in a way that invalidates existing URIs, but has a plan of how these will map to new URIs), then that URI could be advertised in advance (i.e., it is not yet a 3xx, but clients might want to start working with the new URI anyway).

**Comment by dret** [comment]
as discussed elsewhere, it might be useful to include this in a general section that describes when and how to use `Sunset`, and how to use the more basic HTTP 3xx status codes.

**Comment by philsturgeon** [comment]
What do you think about combining `Location` header into a response that has a `Sunset` header, to suggest that a migration is known?

**Comment by dret** [comment]
On 2017-08-08 08:53, Phil Sturgeon wrote:
> What do you think about combining |Location| header into a response that 
> has a |Sunset| header, to suggest that a migration is known?

we can not change the semantics of the `Location` header; it means what 
it means, regardless of whether `Sunset` is there or not.

**Comment by philsturgeon** [comment]
I wasn't aiming to change the semantics of location. If it's not possible to use it then so be it. 

> The "Location" header field is used in some responses to refer to a specific resource in relation to the response. The type of relationship is defined by the combination of request method and status code semantics.

I felt it was a bit open ended and provided some examples of various uses of location (201 created = where the resource is now), and normal 30x stuff. Here difference here I guess is that sunset is only a header, and there's no specific status code for deprecated... that'll mean location cannot just be slapped in?

Ok. Then the migration URL is gonna have to be just part of #72, either in the linkrel, or explained in whatever document the linkrel resolves to. 

--
Phil Sturgeon

**Comment by dret** [comment]
On 2017-08-09 07:08, Phil Sturgeon wrote:
> I wasn't aiming to change the semantics of location. If it's not 
> possible to use it then so be it.

it's possible to use, but keep in mind that most agents will not know 
"Sunset" but will know "Location", and whatever you have in mind to work 
in conjunction with "Sunset" must also work when "Sunset" is ignored.

>  > The "Location" header field is used in some responses to refer to a 
> specific resource in relation to the response. The type of relationship 
> is defined by the combination of request method and status code semantics.
> I felt it was a bit open ended and provided some examples of various 
> uses of location (201 created = where the resource is now), and normal 
> 30x stuff. Here difference here I guess is that sunset is only a header, 
> and there's no specific status code for deprecated... that'll mean 
> location cannot just be slapped in?

it can be, but i think it has to make sense even when "Sunset" is 
ignored. afaict, "Location" is not assigned a specific meaning when used 
in 200 responses.

https://tools.ietf.org/html/rfc7231#section-7.1.2

i am not sure what most implementations would do if they encountered one 
on a 200 response. probably just ignore it? it just seems to me that 
*if* your intended use with "Sunset" is that it should indicate "a 
location in the future (after the sunset)", then that might overload the 
field more than is appropriate.

**Comment by philsturgeon** [comment]
Yeah you're right, it's getting a bit weird. Worth talking it out though.

**Comment by dret** [comment]
getting close to closing this in favor of getting the RFC published without additional complications. anybody objecting make concrete suggestions now, or forever stay silent!

**Comment by dret** [comment]
closing this as part of the final RFC push.
