### ISSUE TITLE
Timestamp in the past

### ISSUE THREAD

**Issue by dret** [dret/I-D#62]
Should it be allowed to have timestamps in the past? Maybe either disallow them, or specifically allow them and explain what they mean, for example the fact that a resource that now is redirecting can expose information about when it changed from being the primary resource to being the redirection.

**Comment by asbjornu** [comment]
Would the other way around make sense too? I.e. that the sunrised resource points to the sunset one? This could probably be achieved with a simple `Link` header relation such as `sunsetting`, `replacing`, `obsoleting`, `superseding`, etc.

While browsing the link relation registry, I just noticed the `successor-version` link relation from [RFC 5289](https://tools.ietf.org/html/rfc5829):

> Points to a resource containing the successor version in the version history.

Not exactly the same as anything covered by the `Sunset` header, but perhaps so closely related that it should be mentioned and its difference should be described?

**Comment by dret** [comment]
On 2017-06-21 14:19, Asbjørn Ulsberg wrote:
> While browsing the link relation registry, I just noticed the
> |successor-version| link relation from RFC 5289
> <https://tools.ietf.org/html/rfc5829>:
>     Points to a resource containing the successor version in the version
>     history.
> Not exactly the same as anything covered by the |Sunset| header, but
> perhaps so closely related that it should be mentioned and its
> difference should be described?

for this i'd argue that sunsetting resources is very different from 
versioning. maybe some versioning does have sunsetting as part of their 
strategy, but that's something in addition and in itself has nothing to 
do with versioning.

otoh, maybe that means that the draft should be explicit that it is 
*not* about versioning? for now, i am simply not mentioning it.

**Comment by dret** [comment]
On 2017-06-21 14:19, Asbjørn Ulsberg wrote:
> Would the other way around make sense too? I.e. that the sunrised
> resource points to the sunset one? This could probably be achieved with
> a simple |Link| header relation such as |sunsetting|, |replacing|,
> |obsoleting|, |superseding|, etc.

interesting thought. let's see if there are any takers!

**Comment by dret** [comment]
this issue may be overcomplicating things. maybe simply add some language to the draft stating that a date in the past has no significance (as far as the draft is concerned) and SHOULD be ignored.

**Comment by philsturgeon** [comment]
I think "SHOULD be ignored" is going to cause some confusion. In the use case of deprecating endpoints, a date in the past means: "Oh boy are you lucky, we said this was going away yesterday but we hit a roadblock and you still have this endpoint for now. Seriously though it could stop working at any point why are you still using this! 💥 "

**Comment by philsturgeon** [comment]
The RFC does not need to take a stance on what it means, but I think suggesting people be wary is a safer bet than suggesting folks don't worry.

**Comment by dret** [comment]
On 2017-08-07 14:50, Phil Sturgeon wrote:
> I think "SHOULD be ignored" is going to cause some confusion. In the use 
> case of deprecating endpoints, a date in the past means: "Oh boy are you 
> lucky, we said this was going away yesterday but we hit a roadblock and 
> you still have this endpoint for now. Seriously though it could stop 
> working at any point why are you still using this! 💥 "

that essentially means "SHOULD consider a date in the past to mean the 
present time", right? maybe that makes more sense.

**Comment by philsturgeon** [comment]
Yeah I think that's what I was gibbering about.

**Comment by dret** [comment]
On 2017-08-07 14:51, Phil Sturgeon wrote:
> The RFC does not need to take a stance on what it means, but I think 
> suggesting people be wary is a safer bet than suggesting folks don't worry.

agreed. so what about:

"Timestamps in the past SHOULD be considered to mean the present time, 
meaning that the resource is expected to become unavailable at any point 
in time."

**Comment by philsturgeon** [comment]
Spot on.

**Comment by dret** [comment]
https://github.com/dret/I-D/commit/35ed46343850ae725aae0eb5e123227fd9001768 adds the proposed text, and if there is no objection, i will close this issue soon.

**Comment by philsturgeon** [comment]
Looks good to me 

--
Phil Sturgeon
