### ISSUE TITLE
handling repeatable target attributes

### ISSUE THREAD

**Issue by dret** [dret/I-D#66]
as mentioned in https://github.com/mnot/I-D/issues/239, one difference between RFC 5988bis and the currently proposed JSON representation is that link parameters cannot be repeated, due to the fact that JSON objects should not contain members with duplicate member names. if the exact model of RFC 5988bis is clarified, we should probably add some explanation of how that translates to the JSON representation, so that mapping between the two representations is a well-defined process.

**Comment by hvdsomp** [comment]
See my comment https://github.com/mnot/I-D/issues/239#issuecomment-319910911

**Comment by dret** [comment]
On 2017-08-03 02:02, Herbert Van de Sompel wrote:
> See my comment mnot/I-D#239 (comment) 

we have to wait and see how https://github.com/mnot/I-D/issues/239 gets 
resolved, and then we can move on with this topic.

**Comment by dret** [comment]
RFC 5988bis will be clarified that `rel` must be present (https://github.com/mnot/I-D/issues/239#issuecomment-321154965), meaning that we can make the same assumption. but this still does not solve the general issue of how to handle repeatable target attributes.

**Comment by dret** [comment]
this is now addressed by various issues. #71 and #73 discuss the repeatability of specific target attributes; #74 discusses the repeatability of generic target attributes.
