### ISSUE TITLE
link context/target vs Context/Target IRI

### ISSUE THREAD

**Issue by hvdsomp** [dret/I-D#69]
It seems that @mnot is confident that RFC5988bis will become the law of the land some time soon. We should probably reflect that in our I-D by moving to "link context" and "link target" language instead of "context IRI" and ""target IRI". I used the following language to make that bridge in the "identifier" I-D:

This specification uses the terms "link context" and "link target" as defined in [I-D.nottingham-rfc5988bis]. These terms respectively correspond with "Context IRI" and "Target IRI" as used in [RFC5988]. Although defined as IRIs, in common scenarios they are also URIs.

**Comment by dret** [comment]
On 2017-08-03 02:41, Herbert Van de Sompel wrote:
> It seems that @mnot <https://github.com/mnot> is confident that 
> RFC5988bis will become the law of the land some time soon. We should 
> probably reflect that in our I-D by moving to "link context" and "link 
> target" language instead of "context IRI" and ""target IRI".

sounds reasonable, and it definitely would be helpful to align 
terminology so that our spec is in line with RFC 5988bis.

**Comment by dret** [comment]
afaict, @hvdsomp's latest proposals makes this terminology change throughout the draft, getting rid of the old RFC 5988 terminology. if that's the case, @hvdsomp, please feel free to close this issue.

**Comment by hvdsomp** [comment]
Indeed, the new version of the I-D will use RFC5899bis terminology throughout. Its Terminology section will make the connection with the RFC5899 terminology.
Closing.
