### ISSUE TITLE
make media types clearly reusable

### ISSUE THREAD

**Issue by dret** [dret/I-D#70]
On 2017-08-03 13:12, Herbert Van de Sompel wrote:

> Regarding "expressing any collection of links, not just link sets": Because the generic format is defined in the same document as the notions of link sets and "linkset" relation type, it is extremely easy to reach the conclusion that the JSON serialization is for link sets. Meaning it should be made explicit that link sets are a special case for which the JSON serialization can be used.

i'd be more than happy to tweak the draft accordingly and make sure that the media type sections are free of any assumptions. generally speaking, though, i don't think that linksets put additional constraints on the *representation* (as discussed in https://github.com/dret/I-D/issues/68#issuecomment-320096956); they simply mean that not all links found in a representation make sense to be considered in linkset scenarios. those links that don't apply to the origin resource can be safely ignored.

**Comment by dret** [comment]
i think we're in agreement that the media types are intended to be reusable outside of the context of the `linkset` link relations. if that's the case, @hvdsomp, please feel free to close this issue.

**Comment by hvdsomp** [comment]
Agreed. And new version of the I-D will make this clear, among others by defining the media types before the "linkset" relation type.
Closing.
