### ISSUE TITLE
add sunset linkrel

### ISSUE THREAD

**Issue by dret** [dret/I-D#72]
as suggested by @philsturgeon (https://github.com/dret/I-D/issues/60#issuecomment-319725579), it would be possible to add a `sunset` link relation that would allow to add links to resources that contain details about the upcoming sunset. these links could then be to human-readable (#59) or machine-readable (#60) resources, which could make it possible to fold these two issues into this one.

**Comment by philsturgeon** [comment]
Hey! implementing rails-sunset I noticed this is still only an issue and not in there. :) 

I'm already starting to wonder if merging human and machine is going to be an issue in the long run, but I guess I'll find out when/if people here start using it!

**Comment by dret** [comment]
On 2017-11-07 17:36, Phil Sturgeon wrote:
> Hey! implementing rails-sunset I noticed this is still only an issue and 
> not in there. :)

adding a `sunset` link relation is easy. so do you think it should be 
done? i like the idea but so far we are the only ones discussing it.

> I'm already starting to wonder if merging human and machine is going to 
> be an issue in the long run, but I guess I'll find out when/if people 
> here start using it!

it's always an issue. but if the header makes the info immediately 
available that's nice and easy for machines. i agree that combining 
https://github.com/dret/I-D/issues/59 and 
https://github.com/dret/I-D/issues/60 in one linkrel may get a bit 
messy. i'd be fine to focus on human-readable resources (assuming that 
the header already makes minimal machine-readable info available). what 
do you think?

**Comment by philsturgeon** [comment]
I'm hoping WeWork will be a source of feedback, but yeah don't go doing stuff because one random guy on the internet agrees. 😅 

I think for now having a `rel="sunset"` link may suffice, and if it rreeeeally sucks then I'll have some use cases for why it sucks. I think my struggles so far are just down to use not having an JSON Schema / OpenAPI anywhere for half the apps we're trying to deprecate stuff out of (which comically is why we're trying to deprecate a bunch of stuff, nobody knows how it works!)

**Comment by dret** [comment]
On 2017-11-07 19:05, Phil Sturgeon wrote:
> I think for now having a |rel="sunset"| link may suffice, and if it 
> rreeeeally sucks then I'll have some use cases for why it sucks. I think 
> my struggles so far are just down to use not having an JSON Schema / 
> OpenAPI anywhere for half the apps we're trying to deprecate stuff out 
> of (which comically is why we're trying to deprecate a bunch of stuff, 
> nobody knows how it works!)

sounds as if adding a linkrel would be a good thing to try, and then 
let's see how people like it.

generally speaking, would the linkrel indicate an upcoming sunset? i 
guess not, it probably would simply link to whatever information is 
available about upcoming sunsets or even just the sunset strategy. so 
there could be a sunset link there all the time, but the sunset header 
field would only start showing up once the clock starts ticking. does 
that sounds reasonable?

**Comment by philsturgeon** [comment]
Yeah I guess the two can be used independently, it doesnt much matter. I'm using them as: if you have further information then please share it. We have some internal APIs with no documentation, and not every deprecated endpoint has a replacement, so some are getting links to the new resource and some are not. 

Sunset and linkrel are both used at the same time when they both exist. I dont do anything special with ordering.

**Comment by dret** [comment]
On 2017-11-08 14:09, Phil Sturgeon wrote:
> Yeah I guess the two can be used independently, it doesnt much matter. 
> I'm using them as: if you have further information then please share it. 
> We have some internal APIs with no documentation, and not every 
> deprecated endpoint has a replacement, so some are getting links to the 
> new resource and some are not.
> Sunset and linkrel are both used at the same time when they both exist. 
> I dont do anything special with ordering.

https://github.com/dret/I-D/commit/918bcbb984378a6a96a872d022a66e9b95969780 
is a proposed new version of the draft (version -04). i'll publish it 
when draft submission is open again (i.e., on sunday). if you have any 
feedback until then, please let me know via comment/issue/PR. thanks!

**Comment by philsturgeon** [comment]
Looks great other than the small gripe commented.

**Comment by dret** [comment]
all good, @philsturgeon? i am assuming it is, if not, please reopen.
