### ISSUE TITLE
wait for RFC 5988 update

### ISSUE THREAD

**Issue by dret** [dret/I-D#75]
https://tools.ietf.org/html/draft-nottingham-rfc5988bis is very close to completion. it may make sense to wait for the new version to be published as an RFC, and update the draft accordingly. it probably needs little more (if anything) than just updating the reference.

**Comment by dret** [comment]
https://tools.ietf.org/html/rfc8288

**Comment by machawk1** [comment]
https://tools.ietf.org/html/rfc5988 still needs an "Obsoleted By: 8288" to be symmetric with RFC8288 stating that it "Obsoletes: 5988".

**Comment by dret** [comment]
true, @machawk1, but that'll probably happen automatically at some point in time, and is an issue for the IETF site. https://github.com/dret/I-D/commit/4fa853bf6d759200180f21952f3e301d5e6d55f5 updates the drafts previously referencing RFC 5988, so this issue can be closed.
