### ISSUE TITLE
Add example to section 4.2.4 of LinkSets spec

### ISSUE THREAD

**Issue by mamund** [dret/I-D#83]
reading through the rules of how extension attributes are expressed is a bit gnarly. would be good to see one or more actual examples that show which extensions MUST use arrays, which not, etc.

https://github.com/dret/I-D/blob/master/linkset/draft-wilde-linkset-01.txt#L512

**Comment by dret** [comment]
On Sep 6, 2017, at 15:48, Mike Amundsen <notifications@github.com> wrote:
> reading through the rules of how extension attributes are expressed is a bit gnarly. would be good to see one or more actual examples that show which extensions MUST use arrays, which not, etc.
> 

all extension attributes must be arrays because every extension attribute may be allowed to repeat. we'll look into where might be a good spot to add examples.

**Comment by mamund** [comment]
Understood.

I got a big confused about arrays when reading points 3 and four on that list. That's where an example would be handy, I think.

**Comment by dret** [comment]
please have a look at the first proposal to resolve this issue. please be aware that it's in the `-02` files, because `-01` has been published.

**Comment by hvdsomp** [comment]
I like the addition of this example. 

I was also wondering whether it would be helpful to add the "rules" that guide the serialization decisions at the outset of the JSON section. I mean by this something like the bullet list under "Overall serialization approach" in #80

**Comment by dret** [comment]
if the proposed example is good enough, please feel free to close this issue.

**Comment by hvdsomp** [comment]
This one is done.
