### ISSUE TITLE
More than one "issues" link

### ISSUE THREAD

**Issue by dret** [dret/I-D#9]
if a resource is associated with more than one "issues" collection (let's assume one for reporting issues with the content, and one for reporting abuse of the content), then how could those links be made distinguishable? there probably should be some guidance or best practice given in the spec.

**Comment by npdoty** [comment]
While it's possible to distinguish a lot of different sub-categories, for example, the sub-categories of abuse, I think there's already a trend in the UX of major services at not exposing that up front. That is, typically sites provide a "report" link or abuse reporting page and then the page has an interactive, human-readable page where users narrow down the category (spam, harassment, sexually explicit, copyright infringing) and provide more detail.

That said, reporting bugs and reporting abuse do often seem quite distinct, and might lead to different endpoints. Abuse is typically reporting violations in user-generated content that are intentionally problematic; bug reports are typically non-controversial information reported to a maintainer of a site.

**Comment by npdoty** [comment]
That might suggest a design with two different `rel` values -- `abuse` and `bugs`, say -- or some guidance on how to indicate to a consumer when there is more than one link which one is likely to be useful to the user for which purpose.

**Comment by dret** [comment]
On 2015-12-05 14:10, Nick Doty wrote:
> While it's possible to distinguish a lot of different sub-categories,
> for example, the sub-categories of abuse, I think there's already a
> trend in the UX of major services at not exposing that up front. That
> is, typically sites provide a "report" link or abuse reporting page and
> then the page has an interactive, human-readable page where users narrow
> down the category (spam, harassment, sexually explicit, copyright
> infringing) and provide more detail.

for the API side of things, it probably also would make sense to have 
one reporting URI and then expect the report to detail the kind of 
report. that implies that all reporting is done to the same service, but 
that may be the most common case anyway.

> That said, reporting bugs and reporting abuse do often seem quite
> distinct, and might lead to different endpoints. Abuse is typically
> reporting violations in user-generated content that are intentionally
> problematic; bug reports are typically non-controversial information
> reported to a maintainer of a site.

that's probably true. the question then is whether these two categories 
are the only two relevant ones, should be treated completely separate, 
or maybe could be folded into one "reporting" pattern that might be able 
to help with both issues/bugs, and reports/abuse.

**Comment by dret** [comment]
On 2015-12-05 14:13, Nick Doty wrote:
> That might suggest a design with two different |rel| values -- |abuse|
> and |bugs|, say -- or some guidance on how to indicate to a consumer
> when there is more than one link which one is likely to be useful to the
> user for which purpose.

if there's two distinct values, then the question is whether these two 
capture the majority of scenarios. if there's one value and some way how 
to specify exactly what to report, then this may be more open to more 
than those two categories, but also might become a bit more complicated.

in terms of link relation types, it's a bit unusual to see these being 
qualified, probably also because that is relatively easy to do in some 
metamodels (XML/HTML come to mind), and more complicated in others (RDF 
and JSON) if you're not resorting to some kind of microsyntax.

**Comment by dret** [comment]
closing because the draft got dropped a long time ago.
