### ISSUE TITLE
RFC 6906: “must not change the semantics of the resource”

### ISSUE THREAD

**Issue by RubenVerborgh** [dret/I-D#93]
RFC 6906 states that

> A profile MUST NOT change the semantics of the
   resource representation when processed without profile knowledge, so
   that clients both with and without knowledge of a profiled resource
   can safely use the same representation.

I think I follow the intention of this statement, but not the exact phrasing. A profile does _change_ the semantics of a representation, in the sense that it adds additional semantics, which constitutes a change:

> a profile can be
   described as additional semantics that can be used to process a
   resource representation

Perhaps a more desirable phrasing is that a profile's additional semantics should not introduce a conflict with the interpretation without that profile?

**Comment by dret** [comment]
On 2018-01-03 05:11, Ruben Verborgh wrote:
> RFC 6906 states that
> 
>     A profile MUST NOT change the semantics of the
>     resource representation when processed without profile knowledge, so
>     that clients both with and without knowledge of a profiled resource
>     can safely use the same representation.
> 
> I think I follow the intention of this statement, but not the exact 
> phrasing. A profile does /change/ the semantics of a representation, in 
> the sense that it adds additional semantics, which constitutes a change:

you are absolutely right. i copied the original text and exactly that 
part needed some fixing what i thought as well. thanks for noticing!

> Perhaps a more desirable phrasing is that a profile's additional 
> semantics should not introduce a conflict with the interpretation 
> without that profile?

sounds good to me. i'll propose something soon. thanks again!

**Comment by dret** [comment]
this one saw one attempt to fix it a little while ago. i'll close it soon unless @RubenVerborgh objects, ideally in an actionable way. thanks!

**Comment by RubenVerborgh** [comment]
The text now reads:

> A profile is defined not to alter the semantics of the resource representation itself, but to allow clients to learn about additional semantics (constraints, conventions, extensions) that are associated with the resource representation, in addition to those defined by the media type and possibly other mechanisms.

This indeed addresses the original issue.

(That said, I wonder what those other mechanisms would be; I think that all semantics should be defined by media type + profile.)
