### ISSUE TITLE
RFC 6906: phrasing regarding media type-independent profiles

### ISSUE THREAD

**Issue by RubenVerborgh** [dret/I-D#95]
RFC 6906 currently reads:

> While this specification
associates profiles with resource representations, creators and users
of profiles MAY define and manage them in a way that allows them to
be used across media types; thus, they could be associated with a
resource, independent of their representations (i.e., using the same
profile URI for different media types).

One could misread this text as stating that:
- a profile is usually associated with a representation of a resource
- IF a profile can be used across media type
- THEN it is necessarily associated with the resource itself

While this is not literally what the text says, it might be perceived as such.

I suggest to rephrase to something like:

> […] creators and users of profiles MAY define and
manage them in a way that allows them to
be used across different media types (i.e., using the same
profile URI for different media types).
In that case, a profile MAY be associated with 
a resource itself, independent of its representations.

**Comment by dret** [comment]
On 2018-01-10 02:29, Ruben Verborgh wrote:
> One could misread this text as stating that:
> 
>   * a profile is usually associated with a representation
>   * IF a profile can be used across media types
>   * THEN it is associated with the resource
>     While this is not literally what the text says, it might be
>     perceived as such.

ok. not the intention. profiles are always for media types, i.e. for 
representations, and never for anything else.

> I suggest to rephrase to something like:
>     In that case, a profile MAY be associated with
>     a resource itself, independent of its representations.

nope, that's not the intention. profiles are always for representations. 
but somebody may reuse the same profile URI for more than one 
representation (which would be inconsequential but may be a design 
decision for people using multiple representations).

**Comment by dret** [comment]
regarding this issue and #93 and #94 as well: did @RubenVerborgh get anything actionable from the survey? if yes, maybe we can create new issues for them, using the lessons learned from the survey? if not, are #93, #94, and #95 still relevant?

**Comment by RubenVerborgh** [comment]
Closed #93 as the required text to clear that up is directly in the RFC now. Replied to #94 with the results of the survey, indicating that clarity there is still missing.

Regarding #95 itself, I read:

> While this specification associates profiles with resource representations, creators and users of profiles MAY define and manage them in a way that allows them to be used across media types;

So that directly addresses the concern I had.
