### ISSUE TITLE
WebHAL should provide require best practices for `_embedded`

### ISSUE THREAD

**Issue by pezra** [dret/I-D#96]
HAL's current hypertext cache system has several weaknesses that result in it being hard to use correctly.

- Clients may interpret the links in certain documents due to ambiguity in the design and spec. A link can occur in the `_embedded` or `_links` section or both. This makes determining the exact set of links for a HAL document difficult an not all clients do it the same way.
- It may require a single representation to be included multiple times. If a single resource is the target of multiple links then it will have to embedded once for each link to eliminate the network traffic.

WebHAL should require:
- that *all* links be listed in the `_links` section, regardless of whether they are also embedded
- that if a rel is used in the `_embedded` section the set of embedded targets exactly match the set of targets in the `_links` section

**Comment by dret** [comment]
i have moved this draft to "abandoned" and will not work on it anymore, since there wasn't enough interest to develop it.
